window.PHOTOGRAPHY_GALLERY = [
  {
    src: "01-open-sky.jpg",
    alt: "A red hot-air balloon floating high above a green farm landscape",
    caption: "Open sky",
    width: 960,
    height: 1280,
  },
  {
    src: "02-tribute-in-light.jpg",
    alt: "Lower Manhattan at night with the Tribute in Light rising into a dark sky",
    caption: "Tribute in Light",
    width: 853,
    height: 1280,
  },
  {
    src: "03-wingbeat.jpg",
    alt: "Birds taking flight above an outstretched gloved hand beside tropical blue water",
    caption: "Wingbeat",
    width: 853,
    height: 1280,
  },
  {
    src: "04-across-the-river.jpg",
    alt: "The illuminated Manhattan skyline reflected across the Hudson River at night",
    caption: "Across the river",
    width: 1280,
    height: 853,
  },
  {
    src: "05-winter-light.jpg",
    alt: "Skiers pausing on a snowy mountain beneath bright winter sun and clouds",
    caption: "Winter light",
    width: 1280,
    height: 960,
  },
  {
    src: "06-waterfront-gathering.jpg",
    alt: "A summer crowd gathered on the Jersey City waterfront with Lower Manhattan beyond",
    caption: "Waterfront gathering",
    width: 960,
    height: 1280,
  },
  {
    src: "07-under-the-stars.jpg",
    alt: "A touring motorcycle beneath a dense night sky filled with stars",
    caption: "Under the stars",
    width: 853,
    height: 1280,
  },
  {
    src: "08-open-road.jpg",
    alt: "A motorcyclist's view down an open road winding through a broad landscape",
    caption: "Open road",
    width: 853,
    height: 1280,
  },
  {
    src: "09-dust-line.jpg",
    alt: "An ATV crossing a dusty field with a cloud-covered mountain in the distance",
    caption: "Dust line",
    width: 1280,
    height: 854,
  },
];
